name: Inclusive Organization
on:
  issues:
    types: [opened]
jobs:
  invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite contributor to the organization
        uses: lekterable/inclusive-organization-action@v1.1.0
        with:
          organization: Spannetjie
          comment: "An invite has been sent to you to join the Spannetjie organization."
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN}}
 
